# Generated by Django 4.1 on 2022-09-25 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0034_alter_user_special_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=5)),
                ('token', models.CharField(max_length=50)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2022, 9, 25, 6, 29, 6, 385917, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 6, 27, 6, 385917, tzinfo=datetime.timezone.utc), verbose_name='کاربر خاص تا زمان:'),
        ),
    ]
