# Generated by Django 4.1 on 2022-09-26 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0044_alter_otc_expiration_date_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techer',
            name='position',
            field=models.CharField(blank=True, choices=[('1', 'توسعه دهنده بک اند'), ('2', 'مدرس و توسعه دهنده'), ('3', 'مدیر وبسایت')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otc',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 17, 53, 17, 919667, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 17, 48, 17, 919667, tzinfo=datetime.timezone.utc), verbose_name='کاربر خاص تا زمان:'),
        ),
    ]
