# Generated by Django 4.1 on 2022-09-26 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0045_techer_position_alter_otc_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 17, 55, 29, 848775, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='techer',
            name='position',
            field=models.CharField(blank=True, choices=[('توسعه دهنده بک اند', 'توسعه دهنده بک اند'), ('مدرس و توسعه دهنده', 'مدرس و توسعه دهنده'), ('مدیر وبسایت', 'مدیر وبسایت')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 17, 50, 29, 833142, tzinfo=datetime.timezone.utc), verbose_name='کاربر خاص تا زمان:'),
        ),
    ]
