# Generated by Django 4.1 on 2022-10-01 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0046_alter_otc_expiration_date_alter_techer_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otc',
            options={'verbose_name': 'کد اعتبارسنجی', 'verbose_name_plural': 'کدهای اعتبارسنجی'},
        ),
        migrations.AlterField(
            model_name='otc',
            name='code',
            field=models.CharField(max_length=5, verbose_name='کد اعتبارسنجی'),
        ),
        migrations.AlterField(
            model_name='otc',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 18, 28, 19, 255037, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد اعتبار سنجی'),
        ),
        migrations.AlterField(
            model_name='otc',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='otc',
            name='token',
            field=models.CharField(max_length=50, verbose_name='توکن اعتبار سنجی'),
        ),
        migrations.AlterField(
            model_name='techer',
            name='position',
            field=models.CharField(blank=True, choices=[('توسعه دهنده بک اند', 'توسعه دهنده بک اند'), ('مدرس', 'مدرس'), ('توسعه دهنده فرانت اند', 'توسعه دهنده فرانت اند'), ('مدرس و توسعه دهنده', 'مدرس و توسعه دهنده'), ('مدیر وبسایت', 'مدیر وبسایت'), (' امنیت و شبکه', 'امنیت و شبکه'), ('توسعه دهنده فلاتر', 'توسعه دهنده فلاتر'), ('توسعه دهنده بلاکچین', 'توسعه دهنده بلاکچین'), ('توسعه دهنده موبایل', 'توسعه دهنده موبایل'), ('برنامه نویس', 'برنامه نویس'), ('متخصص سئو', 'متخصص سئو')], max_length=50, null=True, verbose_name='چه جایگاهی در سایت دارد؟'),
        ),
        migrations.AlterField(
            model_name='techer',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 18, 23, 19, 255037, tzinfo=datetime.timezone.utc), verbose_name='کاربر خاص تا زمان:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, verbose_name='نام کاربری'),
        ),
    ]
