# Generated by Django 4.1 on 2022-10-01 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0047_alter_otc_options_alter_otc_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 19, 0, 48, 535331, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد اعتبار سنجی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 18, 55, 48, 535331, tzinfo=datetime.timezone.utc), verbose_name='کاربر خاص تا زمان:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='نام کاربری'),
        ),
    ]
