# Generated by Django 4.1 on 2022-12-07 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0062_alter_otc_expiration_date_alter_user_special_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='techer',
            name='github',
            field=models.CharField(default='https://www.github.com/', max_length=200),
        ),
        migrations.AddField(
            model_name='techer',
            name='instagram',
            field=models.CharField(default='https://www.instagram.com/', max_length=200),
        ),
        migrations.AddField(
            model_name='techer',
            name='linkedin',
            field=models.CharField(default='https://www.linkedin.com/', max_length=200),
        ),
        migrations.AddField(
            model_name='techer',
            name='twitter',
            field=models.CharField(default='https://twitter.com/', max_length=200),
        ),
        migrations.AlterField(
            model_name='otc',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 0, 59, 8, 161419, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد اعتبار سنجی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 0, 49, 8, 159419, tzinfo=datetime.timezone.utc), verbose_name='کاربر خاص تا زمان:'),
        ),
    ]
