# Generated by Django 4.1 on 2022-12-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorite_app', '0002_alter_favorite_options_alter_favorite_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
