# Generated by Django 4.1 on 2022-12-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_app', '0025_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
    ]
