# Generated by Django 4.1 on 2022-12-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_app', '0027_alter_comment_options_remove_comment_parent_replay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay', to='Tutorial_app.comment', verbose_name='کامنت مرجع'),
        ),
        migrations.DeleteModel(
            name='Replay',
        ),
    ]
